### ISSUE TITLE
ACtividad 1-Mapa mental

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Daisy-GonzalezLita12#1]
ACtividad 1-Mapa mental
Alumna: Daisy Gonzalez Lita
Grupo: 1BS
[Daisy_Gonzalez_Lita_mapa-mental.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Daisy-GonzalezLita12/files/9465370/Daisy_Gonzalez_Lita_mapa-mental.pdf)

**Comment by AmeliReyesHernandez** [comment]
19.4 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
